### PR TITLE
Fix success output for remark

### LINKED ISSUE #206: remark command success message shows raw Person object representation instead of a user-friendly confirmation

### PR DESCRIPTION
**Pull request by amir-hyder**
Fix #206 #244

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/RemarkCommand.java [hunk 1]
```diff
@@ -62,7 +62,8 @@ public CommandResult execute(Model model) throws CommandException {
         Person personToEdit = lastShownList.get(targetIndex.getZeroBased());
 
         personToEdit.addRemark(remark);
-        return new CommandResult(String.format(MESSAGE_ADD_REMARKS_SUCCESS, personToEdit));
+        return new CommandResult(String.format(MESSAGE_ADD_REMARKS_SUCCESS, Messages.format(personToEdit) + "\n"
```
Comment (Isha-Sovasaria) [inline src/main/java/seedu/address/logic/commands/RemarkCommand.java]: Good job on making the output more user-friendly rather than showing the internal implementation details
